export const MOCK_CLIENTS = [
  {
    id: "c1",
    name: "Anand Kumar",
    company: "FinTech Solutions Pvt Ltd",
    email: "anand.kumar@fintech.in",
    phone: "+91 98765 43210",
    status: "Lead",
    leadType: "Hot",
    avatar: "Anand.png",
    joinedDate: "2023-11-15",
    lastContact: "2023-11-20",
    industry: "Financial Services",
    projectCategory: "Tech",
    notes:
      "Very interested in our API integration. Needs a demo by next Tuesday. Decision maker.",
  },
  {
    id: "c2",
    name: "Vikram Malhotra",
    company: "Malhotra Logistics",
    email: "vikram@malhotra.com",
    phone: "+91 98123 45678",
    status: "Lead",
    leadType: "Warm",
    avatar: "https://picsum.photos/100/100?random=12",
    joinedDate: "2023-11-10",
    lastContact: "2023-11-18",
    industry: "Logistics",
    projectCategory: "Tech",
    notes:
      "Checking budget for the next quarter. Currently using a manual system. Open to a pilot program.",
  },
  {
    id: "c3",
    name: "Kavita Rao",
    company: "Urban Health Care",
    email: "kavita.rao@urbanhealth.org",
    phone: "+91 99887 76655",
    status: "Lead",
    leadType: "Cold",
    avatar: "https://picsum.photos/100/100?random=13",
    joinedDate: "2023-10-05",
    lastContact: "2023-11-10",
    industry: "Healthcare",
    projectCategory: "Tech",
    notes:
      "Early stage discussion. Need to follow up in 3 months once their new facility is ready.",
  },
  {
    id: "c4",
    name: "Suresh Raina",
    company: "Nexus Real Estate",
    email: "suresh@nexus.co.in",
    phone: "+91 97654 32109",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=14",
    joinedDate: "2023-01-10",
    lastContact: "2023-11-15",
    industry: "Real Estate",
    projectCategory: "Media",
    notes:
      "Long-term client. Satisfied with the current CRM flow. Looking to upgrade to the enterprise plan.",
  },
  {
    id: "c5",
    name: "Priya Sharma",
    company: "TechVision Inc",
    email: "priya.sharma@techvision.com",
    phone: "+91 98765 12345",
    status: "Active",
    leadType: "Hot",
    avatar: "https://picsum.photos/100/100?random=15",
    joinedDate: "2023-08-20",
    lastContact: "2023-11-22",
    industry: "Technology",
    projectCategory: "Tech",
    notes:
      "Excellent growth trajectory. Very responsive to new features. Expanding team.",
  },
  {
    id: "c6",
    name: "Rajesh Patel",
    company: "Global Trading Solutions",
    email: "rajesh@globaltrading.com",
    phone: "+91 99876 54321",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=16",
    joinedDate: "2023-07-15",
    lastContact: "2023-11-21",
    industry: "Trading",
    projectCategory: "Tech",
    notes:
      "Strategic partner. Regular quarterly reviews. High revenue account.",
  },
  {
    id: "c7",
    name: "Neha Gupta",
    company: "EduTech Academy",
    email: "neha@educator.in",
    phone: "+91 97654 32109",
    status: "Lead",
    leadType: "Warm",
    avatar: "https://picsum.photos/100/100?random=17",
    joinedDate: "2023-10-25",
    lastContact: "2023-11-19",
    industry: "Education",
    projectCategory: "Tech",
    notes: "Interest in student management features. Budget approval pending.",
  },
  {
    id: "c8",
    name: "Arun Verma",
    company: "BuildRight Construction",
    email: "arun@buildright.co.in",
    phone: "+91 98765 11223",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=18",
    joinedDate: "2023-06-10",
    lastContact: "2023-11-20",
    industry: "Construction",
    projectCategory: "Media",
    notes: "Long-standing partner. Multiple project tracking. Very satisfied.",
  },
  {
    id: "c9",
    name: "Deepak Singh",
    company: "RetailMax Networks",
    email: "deepak@retailmax.com",
    phone: "+91 99998 88777",
    status: "Lead",
    leadType: "Cold",
    avatar: "https://picsum.photos/100/100?random=19",
    joinedDate: "2023-11-01",
    lastContact: "2023-11-15",
    industry: "Retail",
    projectCategory: "Tech",
    notes:
      "Inbound inquiry. Evaluating multiple solutions. Demo scheduled for next month.",
  },
  {
    id: "c10",
    name: "Sakshi Mehta",
    company: "HealthCare Plus Hospitals",
    email: "sakshi@healthcareplus.org",
    phone: "+91 98765 00111",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=20",
    joinedDate: "2023-05-12",
    lastContact: "2023-11-22",
    industry: "Healthcare",
    projectCategory: "Tech",
    notes: "Key account. 3 departments using system. Wants advanced analytics.",
  },
  {
    id: "c11",
    name: "Vikram Singh",
    company: "AutoParts Hub",
    email: "vikram.singh@autoparts.in",
    phone: "+91 97777 66655",
    status: "Lead",
    leadType: "Warm",
    avatar: "https://picsum.photos/100/100?random=21",
    joinedDate: "2023-10-30",
    lastContact: "2023-11-18",
    industry: "Automotive",
    projectCategory: "Tech",
    notes:
      "Good fit for our platform. Needs custom integration with ERP system.",
  },
  {
    id: "c12",
    name: "Pooja Desai",
    company: "CloudSync Technologies",
    email: "pooja.d@cloudsync.tech",
    phone: "+91 99999 11223",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=22",
    joinedDate: "2023-04-08",
    lastContact: "2023-11-21",
    industry: "Cloud Services",
    projectCategory: "Tech",
    notes:
      "Technical integration partner. API excellence. Growing partnership.",
  },
  {
    id: "c13",
    name: "Manish Kumar",
    company: "Premium Hotels Group",
    email: "manish.k@premiumhotels.com",
    phone: "+91 98765 55678",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=23",
    joinedDate: "2023-09-14",
    lastContact: "2023-11-20",
    industry: "Hospitality",
    projectCategory: "Media",
    notes:
      "Multi-property rollout. Satisfied with customization. Referral source.",
  },
];

export const MOCK_FOLLOW_UPS = [
  // TODAY - Overdue/Due Today (10)
  {
    id: "f1",
    clientId: "c2",
    projectId: "p5",
    title: "Call James regarding logistics MVP",
    description: "Discuss the MVP scope and timeline",
    dueDate: new Date().toISOString(),
    followup_date: new Date().toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "call",
    follow_brief:
      "Client: Can we speed up the route optimization? Me: We're looking into it, but it might affect the March 15th deadline. Client: Okay, keep me posted.",
  },
  {
    id: "f2",
    clientId: "c1",
    projectId: "p1",
    title: "Send security audit report",
    description: "Complete security audit documentation",
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    followup_date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "email",
    follow_brief:
      "Me: The security audit is 90% complete. Finding some minor issues with the firewall. Client: Understood, please include fix recommendations.",
  },
  {
    id: "f3",
    clientId: "c3",
    title: "Follow up on dashboard latency ticket",
    description: "Check on performance improvement status",
    dueDate: new Date(Date.now() - 172800000).toISOString(),
    followup_date: new Date(Date.now() - 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Low",
    followup_mode: "call",
    projectName: "Healthcare Portal Development",
    follow_brief:
      "Me: Following up on the dashboard latency. Client: It's still a bit slow during the peak hours in the morning. Me: Understood, we're optimizing the queries now. Client: Thanks.",
  },
  {
    id: "f4",
    clientId: "c1",
    projectId: "p4",
    title: "API integration demo session",
    description: "Conduct detailed API integration walkthrough",
    dueDate: new Date(Date.now()).toISOString(),
    followup_date: new Date(Date.now()).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief:
      "Client: I'd like the team to see the sandbox demo. Me: Sure, I'll set up the environment and share the meeting link. Client: Perfect, thanks.",
  },
  {
    id: "f5",
    clientId: "c2",
    title: "Send pricing proposal to Vikram",
    description: "Customized pricing proposal for logistics platform",
    dueDate: new Date(Date.now() - 259200000).toISOString(),
    followup_date: new Date(Date.now() - 259200000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "email",
    projectName: "Logistics MVP Development",
    follow_brief:
      "Me: Pricing proposal sent to Vikram. Client: Received, but we need some room on the volume discounts. Me: Let's discuss this tomorrow. Client: Sure.",
  },
  {
    id: "f6",
    clientId: "c4",
    title: "Upgrade planning session",
    description: "Discuss enterprise plan migration",
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    followup_date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    projectName: "Nexus Enterprise Upgrade",
    follow_brief:
      "Client: We're ready for the upgrade. Me: Great, I'll send over the migration plan. Client: Please ensure the down time is minimal. Me: Of course.",
  },
  {
    id: "f7",
    clientId: "c3",
    title: "Check facility readiness",
    description: "Verify new facility is ready for system deployment",
    dueDate: new Date(Date.now()).toISOString(),
    followup_date: new Date(Date.now()).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Low",
    followup_mode: "call",
    projectName: "Urban Health Facility",
    follow_brief:
      "Me: Is the facility ready for deployment? Client: Almost, just waiting on the final network setup. Me: Let me know once it's done. Client: Will do.",
  },
  {
    id: "f8",
    clientId: "c1",
    title: "Compliance documentation review",
    description: "Review compliance requirements and standards",
    dueDate: new Date(Date.now() - 172800000).toISOString(),
    followup_date: new Date(Date.now() - 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "email",
    projectName: "Security Infrastructure Audit",
    follow_brief: "ISO 27001 and GDPR compliance checklist",
  },
  {
    id: "f16",
    clientId: "c5",
    title: "Quarterly performance review call",
    description: "Review KPIs and discuss growth strategies",
    dueDate: new Date(Date.now()).toISOString(),
    followup_date: new Date(Date.now()).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    projectName: "TechVision Analytics",
    follow_brief: "Q4 performance analysis",
  },
  {
    id: "f17",
    clientId: "c8",
    title: "Check project milestone status",
    description: "Verify all construction phase milestones achieved",
    dueDate: new Date(Date.now() - 345600000).toISOString(),
    followup_date: new Date(Date.now() - 345600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "call",
    projectName: "Project Management Module",
    follow_brief: "Current project status update",
  },

  // UPCOMING - Future dates (10+)
  {
    id: "f9",
    clientId: "c2",
    title: "Integration testing kickoff",
    description: "Start integration testing phase",
    dueDate: new Date(Date.now() + 345600000).toISOString(),
    followup_date: new Date(Date.now() + 345600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    projectName: "Logistics MVP Development",
    follow_brief: "QA plan and testing schedule",
  },
  {
    id: "f10",
    clientId: "c4",
    title: "Quarterly business review",
    description: "Review performance metrics and next quarter goals",
    dueDate: new Date(Date.now() + 604800000).toISOString(),
    followup_date: new Date(Date.now() + 604800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    projectName: "Nexus Real Estate Upgrade",
    follow_brief: "Performance analysis and strategic planning",
  },
  {
    id: "f11",
    clientId: "c3",
    title: "Budget approval follow-up",
    description: "Check on budget allocation status",
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    followup_date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "call",
    projectName: "Urban Health Care Budget",
    follow_brief: "FY budget commitment confirmation",
  },
  {
    id: "f12",
    clientId: "c1",
    title: "User training session scheduling",
    description: "Schedule training for end users",
    dueDate: new Date(Date.now() + 432000000).toISOString(),
    followup_date: new Date(Date.now() + 432000000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "email",
    projectName: "Security Infrastructure Audit",
    follow_brief: "Training calendar and materials preparation",
  },
  {
    id: "f13",
    clientId: "c2",
    title: "Contract finalization call",
    description: "Final contract review and signature",
    dueDate: new Date(Date.now() + 259200000).toISOString(),
    followup_date: new Date(Date.now() + 259200000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "call",
    projectName: "Logistics MVP Contract",
    follow_brief: "Contract amendment discussion and closure",
  },
  {
    id: "f14",
    clientId: "c4",
    title: "Support team handover",
    description: "Transfer account to dedicated support team",
    dueDate: new Date(Date.now() + 172800000).toISOString(),
    followup_date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Low",
    followup_mode: "email",
    follow_brief: "Introduce support team and escalation process",
  },
  {
    id: "f15",
    clientId: "c3",
    title: "Demo with stakeholders",
    description: "Present solution to hospital stakeholders",
    dueDate: new Date(Date.now() + 518400000).toISOString(),
    followup_date: new Date(Date.now() + 518400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    projectName: "Urban Health Stakeholder Demo",
    follow_brief: "Live platform demo and Q&A session",
  },
  {
    id: "f18",
    clientId: "c6",
    title: "Executive steering committee meeting",
    description: "Present platform ROI metrics and future roadmap",
    dueDate: new Date(Date.now() + 777600000).toISOString(),
    followup_date: new Date(Date.now() + 777600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    projectName: "Global Trading Pipeline",
    follow_brief: "Executive level discussion on strategic initiatives",
  },
  {
    id: "f19",
    clientId: "c7",
    title: "Student management feature walkthrough",
    description:
      "Show EduTech team comprehensive student tracking capabilities",
    dueDate: new Date(Date.now() + 172800000).toISOString(),
    followup_date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    projectName: "EduTech Feature Walkthrough",
    follow_brief: "Education-specific features demo",
  },
  {
    id: "f20",
    clientId: "c9",
    title: "RetailMax store manager training",
    description: "Train on-site team on system functionalities",
    dueDate: new Date(Date.now() + 864000000).toISOString(),
    followup_date: new Date(Date.now() + 864000000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    projectName: "RetailMax Network Training",
    follow_brief: "Multi-store training program",
  },
  {
    id: "f21",
    clientId: "c10",
    title: "Healthcare compliance audit",
    description: "Verify system meets HIPAA requirements",
    dueDate: new Date(Date.now() + 432000000).toISOString(),
    followup_date: new Date(Date.now() + 432000000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    projectName: "Healthcare Compliance Hub",
    follow_brief: "Compliance verification and certification",
  },
  {
    id: "f22",
    clientId: "c11",
    title: "ERP integration planning",
    description: "Discuss technical architecture and data mapping",
    dueDate: new Date(Date.now() + 604800000).toISOString(),
    followup_date: new Date(Date.now() + 604800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    projectName: "AutoParts ERP Sync",
    follow_brief: "ERP system integration specifications",
  },
  {
    id: "f23",
    clientId: "c12",
    title: "API partner integration review",
    description: "Technical review of API integration capabilities",
    dueDate: new Date(Date.now() + 345600000).toISOString(),
    followup_date: new Date(Date.now() + 345600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    projectName: "CloudSync API Review",
    follow_brief: "API documentation and sandbox access",
  },
];

export const MOCK_PROJECTS = [
  // PENDING - Status: Pending (10)
  {
    id: "p1",
    clientId: "c1",
    name: "Security Infrastructure Audit",
    status: "Planning",
    budget: 45000,
    deadline: "2026-03-15",
    progress: 15,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p2",
    clientId: "c3",
    name: "Healthcare Portal Development",
    status: "Planning",
    budget: 85000,
    deadline: "2026-04-20",
    progress: 5,
    priority: "Critical",
    category: "Tech",
    description:
      "Build a patient-facing healthcare portal with appointment management, medical records, and telemedicine capabilities.",
  },
  {
    id: "p3",
    clientId: "c7",
    name: "EduTech Platform Integration",
    status: "Planning",
    budget: 35000,
    deadline: "2026-03-30",
    progress: 0,
    priority: "High",
    category: "Tech",
    description:
      "Integrate learning management system with existing educational platform to streamline course delivery.",
  },
  {
    id: "p15",
    clientId: "c9",
    name: "Retail CRM Setup",
    status: "Planning",
    budget: 50000,
    deadline: "2026-05-01",
    progress: 10,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p16",
    clientId: "c10",
    name: "Healthcare Analytics Module",
    status: "Planning",
    budget: 90000,
    deadline: "2026-06-10",
    progress: 2,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p17",
    clientId: "c11",
    name: "Auto Parts Inventory Sync",
    status: "Planning",
    budget: 30000,
    deadline: "2026-04-25",
    progress: 0,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p18",
    clientId: "c12",
    name: "Cloud Backup Implementation",
    status: "Planning",
    budget: 40000,
    deadline: "2026-05-15",
    progress: 5,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p19",
    clientId: "c13",
    name: "Hotel Loyalty Program Integration",
    status: "Pending",
    budget: 55000,
    deadline: "2026-06-30",
    progress: 0,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p20",
    clientId: "c5",
    name: "Analytics AI Module",
    status: "Pending",
    budget: 65000,
    deadline: "2026-05-20",
    progress: 8,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p21",
    clientId: "c6",
    name: "Trading Data Pipeline",
    status: "Pending",
    budget: 72000,
    deadline: "2026-06-05",
    progress: 12,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p41",
    clientId: "c8",
    name: "Media Asset Library Setup",
    status: "Pending",
    budget: 30000,
    deadline: "2026-05-12",
    progress: 5,
    priority: "Medium",
    category: "Media",
  },
  {
    id: "p42",
    clientId: "c9",
    name: "Social Campaign Planning",
    status: "Pending",
    budget: 45000,
    deadline: "2026-05-25",
    progress: 8,
    priority: "High",
    category: "Media",
  },
  {
    id: "p43",
    clientId: "c10",
    name: "Video Production Coordination",
    status: "Pending",
    budget: 60000,
    deadline: "2026-06-10",
    progress: 2,
    priority: "High",
    category: "Media",
  },

  // IN PROGRESS - Status: In Progress (10)
  {
    id: "p4",
    clientId: "c1",
    name: "API Integration Phase 2",
    status: "In Progress",
    budget: 55000,
    deadline: "2026-02-28",
    progress: 65,
    priority: "High",
    category: "Tech",
    description:
      "Second phase of API integration connecting CRM with third-party payment processors and analytics tools.",
  },
  {
    id: "p5",
    clientId: "c2",
    name: "Logistics MVP Development",
    status: "In Progress",
    budget: 120000,
    deadline: "2026-03-15",
    progress: 58,
    priority: "Critical",
    category: "Tech",
    description:
      "Building minimum viable product for logistics management with route optimization and real-time tracking.",
  },
  {
    id: "p6",
    clientId: "c5",
    name: "Analytics Dashboard Enhancement",
    status: "In Progress",
    budget: 28000,
    deadline: "2026-02-15",
    progress: 72,
    priority: "Medium",
    category: "Tech",
    description:
      "Upgrade existing analytics dashboard with new visualization components and advanced filtering capabilities.",
  },
  {
    id: "p7",
    clientId: "c8",
    name: "Project Management Module",
    status: "In Progress",
    budget: 64000,
    deadline: "2026-03-20",
    progress: 45,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p22",
    clientId: "c9",
    name: "Retail POS Integration",
    status: "In Progress",
    budget: 48000,
    deadline: "2026-03-05",
    progress: 33,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p23",
    clientId: "c10",
    name: "Hospital Scheduling Module",
    status: "In Progress",
    budget: 110000,
    deadline: "2026-03-25",
    progress: 50,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p24",
    clientId: "c11",
    name: "Inventory Forecast Engine",
    status: "In Progress",
    budget: 36000,
    deadline: "2026-03-10",
    progress: 27,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p25",
    clientId: "c12",
    name: "Cloud Security Audit",
    status: "In Progress",
    budget: 39000,
    deadline: "2026-02-28",
    progress: 60,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p26",
    clientId: "c13",
    name: "Hotel Reservation API",
    status: "In Progress",
    budget: 82000,
    deadline: "2026-03-22",
    progress: 40,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p27",
    clientId: "c1",
    name: "Security Patch Rollout",
    status: "In Progress",
    budget: 22000,
    deadline: "2026-03-01",
    progress: 80,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p44",
    clientId: "c5",
    name: "Podcast Series Editing",
    status: "In Progress",
    budget: 27000,
    deadline: "2026-03-12",
    progress: 40,
    priority: "Medium",
    category: "Media",
  },
  {
    id: "p45",
    clientId: "c7",
    name: "Banner Ad Design",
    status: "In Progress",
    budget: 15000,
    deadline: "2026-03-08",
    progress: 55,
    priority: "Low",
    category: "Media",
  },
  {
    id: "p46",
    clientId: "c9",
    name: "Influencer Outreach",
    status: "In Progress",
    budget: 38000,
    deadline: "2026-03-18",
    progress: 30,
    priority: "High",
    category: "Media",
  },

  // TESTING - Status: Testing (10)
  {
    id: "p8",
    clientId: "c4",
    name: "Enterprise Upgrade Implementation",
    status: "Testing",
    budget: 92000,
    deadline: "2026-02-10",
    progress: 82,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p9",
    clientId: "c6",
    name: "Trading Platform Optimization",
    status: "Testing",
    budget: 78000,
    deadline: "2026-02-20",
    progress: 88,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p10",
    clientId: "c12",
    name: "Cloud Infrastructure Migration",
    status: "Testing",
    budget: 145000,
    deadline: "2026-02-28",
    progress: 91,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p28",
    clientId: "c2",
    name: "Logistics Tracking Beta",
    status: "Testing",
    budget: 60000,
    deadline: "2026-02-25",
    progress: 75,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p29",
    clientId: "c3",
    name: "Health App Feedback Module",
    status: "Testing",
    budget: 47000,
    deadline: "2026-02-22",
    progress: 68,
    priority: "Low",
    category: "Tech",
  },
  {
    id: "p30",
    clientId: "c5",
    name: "Analytics Beta Feature",
    status: "Testing",
    budget: 29000,
    deadline: "2026-02-18",
    progress: 83,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p31",
    clientId: "c7",
    name: "Edu Portal Load Test",
    status: "Testing",
    budget: 32000,
    deadline: "2026-02-26",
    progress: 90,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p32",
    clientId: "c8",
    name: "Construction Ticket System",
    status: "Testing",
    budget: 56000,
    deadline: "2026-02-24",
    progress: 70,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p33",
    clientId: "c9",
    name: "Retail Checkout UX",
    status: "Testing",
    budget: 41000,
    deadline: "2026-02-27",
    progress: 95,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p34",
    clientId: "c10",
    name: "Hospital API Compliance",
    status: "Testing",
    budget: 88000,
    deadline: "2026-02-29",
    progress: 89,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p47",
    clientId: "c11",
    name: "Media Analytics Tool",
    status: "Completed",
    budget: 52000,
    deadline: "2026-02-26",
    progress: 100,
    priority: "High",
    category: "Media",
  },
  {
    id: "p48",
    clientId: "c12",
    name: "Ad Platform Integration",
    status: "Completed",
    budget: 61000,
    deadline: "2026-02-28",
    progress: 100,
    priority: "Medium",
    category: "Media",
  },

  // LIVE - Status: Live (10)
  {
    id: "p11",
    clientId: "c4",
    name: "CRM Platform Maintenance",
    status: "Live",
    budget: 25000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p12",
    clientId: "c10",
    name: "Hospital Management System",
    status: "Live",
    budget: 175000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p13",
    clientId: "c13",
    name: "Hotel Booking & Management",
    status: "Live",
    budget: 95000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p14",
    clientId: "c11",
    name: "Parts Inventory Tracking",
    status: "Live",
    budget: 42000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p35",
    clientId: "c1",
    name: "Security Maintenance Live",
    status: "Live",
    budget: 30000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p36",
    clientId: "c2",
    name: "Logistics Client Portal",
    status: "Live",
    budget: 110000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p37",
    clientId: "c3",
    name: "Healthcare Data Sync",
    status: "Live",
    budget: 60000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p38",
    clientId: "c5",
    name: "Analytics Module Live",
    status: "Live",
    budget: 45000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p39",
    clientId: "c6",
    name: "Trading Platform Live",
    status: "Live",
    budget: 80000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p40",
    clientId: "c7",
    name: "Edu Portal Live",
    status: "Live",
    budget: 50000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p49",
    clientId: "c8",
    name: "Social Media Dashboard",
    status: "Completed",
    budget: 42000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Medium",
    category: "Media",
  },
  {
    id: "p50",
    clientId: "c10",
    name: "Broadcast Automation",
    status: "Completed",
    budget: 90000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Media",
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: "a1",
    clientId: "c1",
    type: "email",
    description: "Sent weekly security report",
    date: "2023-10-25T14:30:00",
  },
  {
    id: "a2",
    clientId: "c2",
    type: "call",
    description: "Introductory call with James",
    date: "2023-10-28T10:00:00",
  },
  {
    id: "a3",
    clientId: "c1",
    type: "meeting",
    description: "API integration planning session",
    date: "2023-11-15T11:00:00",
  },
  {
    id: "a4",
    clientId: "c4",
    type: "email",
    description: "Sent Q4 performance metrics report",
    date: "2023-11-20T09:30:00",
  },
  {
    id: "a5",
    clientId: "c2",
    type: "call",
    description: "Budget approval discussion",
    date: "2023-11-18T14:15:00",
  },
  {
    id: "a6",
    clientId: "c3",
    type: "email",
    description: "Sent facility audit checklist",
    date: "2023-11-17T16:45:00",
  },
  {
    id: "a7",
    clientId: "c5",
    type: "meeting",
    description: "Demo of new analytics dashboard",
    date: "2023-11-16T10:00:00",
  },
  {
    id: "a8",
    clientId: "c6",
    type: "call",
    description: "Market expansion strategy discussion",
    date: "2023-11-19T15:30:00",
  },
  {
    id: "a9",
    clientId: "c8",
    type: "email",
    description: "Construction project milestone review",
    date: "2023-11-21T13:00:00",
  },
  {
    id: "a10",
    clientId: "c10",
    type: "meeting",
    description: "Healthcare compliance verification",
    date: "2023-11-22T11:30:00",
  },
  {
    id: "a11",
    clientId: "c7",
    type: "call",
    description: "Student management features walkthrough",
    date: "2023-11-20T14:00:00",
  },
  {
    id: "a12",
    clientId: "c12",
    type: "email",
    description: "API partnership documentation sent",
    date: "2023-11-19T09:45:00",
  },
];

export const MOCK_ENQUIRIES = [
  {
    id: "s101",
    name: "SEO Booster",
    email: "rank@seofasttop.com",
    phone: "",
    website: "https://seofasttop.com",
    message:
      "We can rank your website #1 on Google within 24 hours. Buy 20,000 backlinks for only $49.",
    date: "2023-11-24T10:10:00",
    status: "new",
  },
  {
    id: "s102",
    name: "Crypto Profit System",
    email: "auto@cryptoprofits.io",
    phone: "",
    website: "https://cryptoprofits.io",
    message:
      "Earn $10,000 per week with our automated crypto trading bot. No experience needed.",
    date: "2023-11-24T10:30:00",
    status: "new",
  },
  {
    id: "s103",
    name: "Casino Deals",
    email: "promo@supercasino.bet",
    phone: "",
    website: "https://supercasino.bet",
    message:
      "Play online casino and win real money instantly. 500% signup bonus today!",
    date: "2023-11-24T11:00:00",
    status: "new",
  },
  {
    id: "s104",
    name: "Adult Ads Network",
    email: "ads@adulttrafficnetwork.com",
    phone: "",
    website: "https://adulttrafficnetwork.com",
    message:
      "Promote your adult website and get millions of visitors daily. Join our ad network.",
    date: "2023-11-24T11:20:00",
    status: "new",
  },
  {
    id: "s105",
    name: "Cheap Loans",
    email: "loan@instantfunds.co",
    phone: "",
    website: "https://instantfunds.co",
    message:
      "Need urgent cash? Get personal loans up to $50,000 approved in 10 minutes.",
    date: "2023-11-24T11:45:00",
    status: "new",
  },
  {
    id: "s106",
    name: "Link Exchange Team",
    email: "links@linkpartner.net",
    phone: "",
    website: "https://linkpartner.net",
    message:
      "We would like to exchange backlinks with your website for SEO purposes.",
    date: "2023-11-24T12:10:00",
    status: "new",
  },
  {
    id: "s107",
    name: "Web Traffic Seller",
    email: "traffic@visitorsboost.io",
    phone: "",
    website: "https://visitorsboost.io",
    message:
      "Buy 1 million website visitors for only $20. Instant traffic guaranteed.",
    date: "2023-11-24T12:30:00",
    status: "new",
  },
  {
    id: "s108",
    name: "Hacker Services",
    email: "services@hacksolutions.pro",
    phone: "",
    website: "https://hacksolutions.pro",
    message:
      "Need to hack a social media account or recover lost passwords? Contact us.",
    date: "2023-11-24T12:50:00",
    status: "new",
  },
  {
    id: "s109",
    name: "Fake Pharmacy",
    email: "sales@cheapmeds-online.net",
    phone: "",
    website: "https://cheapmeds-online.net",
    message:
      "Buy medicines online without prescription. Huge discounts available.",
    date: "2023-11-24T13:15:00",
    status: "new",
  },
  {
    id: "s110",
    name: "Essay Writer",
    email: "help@essayghostwriters.com",
    phone: "",
    website: "https://essayghostwriters.com",
    message:
      "We write essays, assignments and dissertations for students at cheap prices.",
    date: "2023-11-24T13:40:00",
    status: "new",
  },
  {
    id: "s111",
    name: "Random Bot",
    email: "bot@unknown.xyz",
    phone: "",
    website: "",
    message: "asdkjhasd kjashd kjashdkjashd kjashd kjashdkj",
    date: "2023-11-24T14:00:00",
    status: "new",
  },
  {
    id: "s112",
    name: "Weight Loss Pills",
    email: "diet@fatburnerworld.com",
    phone: "",
    website: "https://fatburnerworld.com",
    message:
      "Lose 10kg in 7 days with our miracle weight loss pills. Order today.",
    date: "2023-11-24T14:20:00",
    status: "new",
  },
  {
    id: "s113",
    name: "NFT Investment",
    email: "invest@nftfortune.io",
    phone: "",
    website: "https://nftfortune.io",
    message: "Invest in NFT projects and double your money in a week.",
    date: "2023-11-24T14:40:00",
    status: "new",
  },
  {
    id: "s114",
    name: "Domain Seller",
    email: "domains@premiumdomainsales.com",
    phone: "",
    website: "https://premiumdomainsales.com",
    message:
      "We noticed your website. Would you like to buy premium domains related to your niche?",
    date: "2023-11-24T15:00:00",
    status: "new",
  },
  {
    id: "s115",
    name: "Telegram Marketing",
    email: "promo@telegramgrowth.net",
    phone: "",
    website: "https://telegramgrowth.net",
    message: "Get 50,000 Telegram members instantly for your group or channel.",
    date: "2023-11-24T15:20:00",
    status: "new",
  },
  {
    id: "s116",
    name: "YouTube Booster",
    email: "views@youtubeboost.io",
    phone: "",
    website: "https://youtubeboost.io",
    message: "Buy YouTube subscribers, likes and views instantly.",
    date: "2023-11-24T15:40:00",
    status: "new",
  },
  {
    id: "s117",
    name: "Completely Irrelevant",
    email: "farmer@villagefarm.in",
    phone: "+91 88888 00000",
    website: "",
    message: "Do you sell tractor spare parts? I need farming equipment.",
    date: "2023-11-24T16:00:00",
    status: "irrelevant",
  },
  {
    id: "s118",
    name: "Interior Contractor",
    email: "design@homespace.in",
    phone: "+91 91234 56789",
    website: "",
    message: "We are looking for interior contractors for house renovation.",
    date: "2023-11-24T16:20:00",
    status: "irrelevant",
  },
  {
    id: "s119",
    name: "Job Seeker",
    email: "candidate@gmail.com",
    phone: "+91 99999 44444",
    website: "",
    message: "Please give me job in your company. I need work urgently.",
    date: "2023-11-24T16:40:00",
    status: "irrelevant",
  },
  {
    id: "s120",
    name: "Test Entry",
    email: "test@test.com",
    phone: "",
    website: "",
    message: "test test test test test",
    date: "2023-11-24T17:00:00",
    status: "new",
  },
  {
    id: "e36",
    name: "Rahul Sharma",
    email: "rahul@trendkart.in",
    phone: "+91 98765 43210",
    website: "https://trendkart.in",
    message:
      "We are planning to launch an ecommerce website for our clothing brand. Need website development and SEO services.",
    date: "2023-11-23T10:20:00",
    status: "new",
  },
  {
    id: "e37",
    name: "Ananya Reddy",
    email: "ananya@healthplusclinic.com",
    phone: "+91 90000 11111",
    website: "https://healthplusclinic.com",
    message:
      "We need a website for our healthcare clinic along with Google SEO optimization and social media marketing.",
    date: "2023-11-23T11:40:00",
    status: "new",
  },
  {
    id: "e38",
    name: "Daniel Cooper",
    email: "daniel@cooperconsulting.com",
    phone: "+1 (555) 777-2222",
    website: "https://cooperconsulting.com",
    message:
      "Looking to redesign our company website using modern UI/UX and improve our online presence.",
    date: "2023-11-23T12:15:00",
    status: "new",
  },
  {
    id: "e39",
    name: "Priya Nair",
    email: "priya@edulearn.in",
    phone: "+91 81234 56789",
    website: "https://edulearn.in",
    message:
      "We want to build a mobile learning app for students. Can your team help with mobile app development?",
    date: "2023-11-23T13:10:00",
    status: "new",
  },
  {
    id: "e40",
    name: "Arjun Mehta",
    email: "arjun@buildmart.in",
    phone: "+91 99887 77665",
    website: "https://buildmart.in",
    message:
      "Looking for digital marketing and brand promotion services to increase online visibility of our construction business.",
    date: "2023-11-23T14:20:00",
    status: "new",
  },
  {
    id: "e41",
    name: "Ramesh Kumar",
    email: "ramesh@gmail.com",
    phone: "+91 88888 77777",
    website: "",
    message:
      "Hi, I am looking for a job as a frontend developer in your company. Please let me know if there are openings.",
    date: "2023-11-23T15:00:00",
    status: "new",
  },
  {
    id: "e42",
    name: "Vikram Singh",
    email: "vikram@agrotools.in",
    phone: "+91 98700 12345",
    website: "https://agrotools.in",
    message:
      "We are looking for agricultural equipment suppliers for our farm project.",
    date: "2023-11-23T16:20:00",
    status: "new",
  },
  {
    id: "e43",
    name: "Meera Patel",
    email: "meera@interiorspace.in",
    phone: "+91 90123 45678",
    website: "https://interiorspace.in",
    message: "Do you provide interior design services for office spaces?",
    date: "2023-11-23T17:10:00",
    status: "new",
  },
  {
    id: "e44",
    name: "Backlink Seller",
    email: "seo@10000-backlinks.com",
    phone: "",
    website: "https://10000-backlinks.com",
    message:
      "Buy 10,000 high authority backlinks and rank #1 on Google instantly! Special offer only $29.",
    date: "2023-11-23T18:00:00",
    status: "new",
  },
  {
    id: "e45",
    name: "Crypto Investor",
    email: "profit@cryptomillions.biz",
    phone: "",
    website: "https://cryptomillions.biz",
    message:
      "Earn $5000 per day trading crypto automatically. Join our investment program today!",
    date: "2023-11-23T19:10:00",
    status: "new",
  },
  {
    id: "e46",
    name: "Karan Gupta",
    email: "karan@cityfoods.in",
    phone: "+91 98765 22211",
    website: "https://cityfoods.in",
    message:
      "Our company website needs regular maintenance and updates. Do you provide AMC plans for website maintenance?",
    date: "2023-11-25T09:20:00",
    status: "new",
  },
  {
    id: "e47",
    name: "Sneha Kulkarni",
    email: "sneha@fintrack.in",
    phone: "+91 90111 22334",
    website: "https://fintrack.in",
    message:
      "We are looking for a WordPress developer to build a finance blog with custom plugins and SEO optimization.",
    date: "2023-11-25T10:10:00",
    status: "new",
  },
  {
    id: "e48",
    name: "Michael Brown",
    email: "michael@startuphub.io",
    phone: "+1 555 111 8899",
    website: "https://startuphub.io",
    message:
      "We want to build a web application for startup collaboration. Can your team develop a scalable web app?",
    date: "2023-11-25T10:45:00",
    status: "new",
  },
  {
    id: "e49",
    name: "Ritika Sharma",
    email: "ritika@stylevilla.in",
    phone: "+91 98700 45678",
    website: "https://stylevilla.in",
    message:
      "Our WordPress website is slow and outdated. We need a redesign and performance optimization.",
    date: "2023-11-25T11:30:00",
    status: "new",
  },
  {
    id: "e50",
    name: "David Lee",
    email: "david@marketboost.com",
    phone: "+1 555 444 2233",
    website: "https://marketboost.com",
    message:
      "We need a full website SEO audit and technical audit to identify issues affecting our rankings.",
    date: "2023-11-25T12:05:00",
    status: "new",
  },
  {
    id: "e51",
    name: "Neha Agarwal",
    email: "neha@eduacademy.in",
    phone: "+91 99888 12345",
    website: "https://eduacademy.in",
    message:
      "Do you provide WordPress website AMC services including backups, plugin updates and security monitoring?",
    date: "2023-11-25T12:40:00",
    status: "new",
  },
  {
    id: "e52",
    name: "Sanjay Verma",
    email: "sanjay@buildzone.in",
    phone: "+91 90090 11223",
    website: "https://buildzone.in",
    message:
      "We want to migrate our existing website to WordPress and require ongoing maintenance support.",
    date: "2023-11-25T13:15:00",
    status: "new",
  },
  {
    id: "e53",
    name: "Olivia Wilson",
    email: "olivia@techreviewhub.com",
    phone: "+44 7700 900123",
    website: "https://techreviewhub.com",
    message:
      "Looking for a website performance audit and security audit to improve our site speed and security.",
    date: "2023-11-25T14:00:00",
    status: "new",
  },
  {
    id: "e54",
    name: "Amit Bansal",
    email: "amit@shopnext.in",
    phone: "+91 98111 55667",
    website: "https://shopnext.in",
    message:
      "We need a custom WordPress ecommerce website along with long-term AMC support.",
    date: "2023-11-25T14:35:00",
    status: "new",
  },
  {
    id: "e55",
    name: "Sophia Martinez",
    email: "sophia@healthtechsolutions.com",
    phone: "+1 555 999 1212",
    website: "https://healthtechsolutions.com",
    message:
      "Our healthcare platform requires a web application dashboard and API integration. Can your team help?",
    date: "2023-11-25T15:20:00",
    status: "new",
  },
];

export const ANALYTICS_DATA = [
  { name: "May", enquiries: 12, clients: 8, projects: 2, engagement: 65 },
  { name: "Jun", enquiries: 18, clients: 10, projects: 4, engagement: 72 },
  { name: "Jul", enquiries: 15, clients: 12, projects: 5, engagement: 70 },
  { name: "Aug", enquiries: 24, clients: 15, projects: 6, engagement: 78 },
  { name: "Sep", enquiries: 32, clients: 18, projects: 9, engagement: 82 },
  { name: "Oct", enquiries: 28, clients: 22, projects: 12, engagement: 88 },
];

export const QUARTERLY_ANALYTICS_DATA = [
  { name: "Q1 2023", enquiries: 45, clients: 32, projects: 8, engagement: 62 },
  { name: "Q2 2023", enquiries: 58, clients: 40, projects: 12, engagement: 70 },
  { name: "Q3 2023", enquiries: 75, clients: 55, projects: 18, engagement: 79 },
  { name: "Q4 2023", enquiries: 88, clients: 68, projects: 24, engagement: 85 },
];
